import {safeOrganizationImage} from './organizations.js';
import {adminTemplate} from './admin-template.js';

import {adminMetrics,organizationFilter,verificationState,adminError} from './admin-data.js';

import {listingStatus,FOOD_LABELS,safeFoodImage,timestampMillis} from './listing-model.js';



import {mountEngagement} from './engagement.js';



export function mountAdmin(root,{sdk,user,profile,repository,logout}){

 root.innerHTML=adminTemplate();const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)],abort=new AbortController(),on=(target,event,fn)=>target.addEventListener(event,fn,{signal:abort.signal});

 const motion=matchMedia('(prefers-reduced-motion:reduce)'),mobile=matchMedia('(max-width:800px)'),names=['users','listings','claims','adminActivity'],state=Object.fromEntries(names.map(name=>[name,{items:[],ready:false,cache:true,error:null,stop:null,generation:0}]));

 let verificationTab='pending',panel='overview',dead=false,busy=false,operation,opener,detailToken=0,toastTimer,animated=false;const pages={directory:0,listings:0,claims:0},animations=new Set();

 const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};

 const date=value=>timestampMillis(value)?new Date(timestampMillis(value)).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Awaiting timestamp';

 const role=value=>value==='hostel'?'Hostel':value==='ngo'?'NGO':'Admin';

 const partner=id=>state.users.items.find(u=>u.uid===id),food=id=>state.listings.items.find(l=>l.id===id),fresh=name=>state[name].ready&&!state[name].cache&&!state[name].error;

 function animate(options){if(motion.matches||!window.anime)return;let a;const complete=options.complete;a=anime({...options,complete:()=>{animations.delete(a);complete?.();}});animations.add(a);}

 function syncTheme(){$('#admin-theme').value=MealBridgeTheme.preference;}syncTheme();on(document,'mealbridge:theme',syncTheme);on($('#admin-theme'),'change',()=>MealBridgeTheme.set($('#admin-theme').value));

 function closeMenu(restore=false){$('#admin-sidebar').classList.remove('is-open');$('#admin-sidebar').inert=mobile.matches;$('.db-body').inert=false;$('#admin-scrim').hidden=true;$('#admin-menu').setAttribute('aria-expanded','false');document.body.classList.remove('db-dialog-open');if(restore)$('#admin-menu').focus();}

 closeMenu();on(mobile,'change',()=>closeMenu());on($('#admin-menu'),'click',()=>{if($('#admin-sidebar').classList.contains('is-open')){closeMenu(true);return;}$('#admin-sidebar').inert=false;$('#admin-sidebar').classList.add('is-open');$('.db-body').inert=true;$('#admin-scrim').hidden=false;$('#admin-menu').setAttribute('aria-expanded','true');document.body.classList.add('db-dialog-open');$('.db-nav button').focus();animate({targets:$('.db-nav'),translateX:[-8,0],duration:250,easing:'easeOutExpo'});});on($('#admin-scrim'),'click',()=>closeMenu(true));

 on(document,'keydown',e=>{if(!$('#admin-sidebar').classList.contains('is-open'))return;if(e.key==='Escape'){e.preventDefault();closeMenu(true);}if(e.key==='Tab'){const controls=[...$('#admin-sidebar').querySelectorAll('a,button')],first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});

 function showPanel(name){if(!['overview','verification','directory','listings','claims','analytics'].includes(name))return;panel=name;$$('[data-section]').forEach(s=>s.hidden=s.dataset.section!==name);$$('.db-nav [data-panel]').forEach(b=>{if(b.dataset.panel===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});closeMenu();renderPanel();window.scrollTo({top:0,behavior:'instant'});$(`#${name}-title`).focus({preventScroll:true});}

 function toast(text){clearTimeout(toastTimer);const region=$('#admin-confirm').open?$('#admin-inline-toast'):$('#admin-toast');region.replaceChildren();const box=node('div','db-toast'),label=node('span','',text),close=node('button','','×');close.type='button';close.setAttribute('aria-label','Dismiss notification');close.addEventListener('click',()=>box.remove(),{once:true});box.append(label,close);region.append(box);animate({targets:box,translateY:[8,0],duration:250,easing:'easeOutExpo'});toastTimer=setTimeout(()=>box.remove(),10000);}

 function badge(value){return node('span','db-pill ad-badge-'+value,value[0].toUpperCase()+value.slice(1));}

 function button(label,action,id,disabled=false,cls='db-text-button'){const b=node('button',cls,label);b.type='button';b.dataset.action=action;b.dataset.id=id;b.disabled=disabled;return b;}

 function fields(pairs){const dl=node('dl','ad-fields');for(const [label,value]of pairs){const group=node('div'),dt=node('dt','',label),dd=node('dd','',value||'Not provided');group.append(dt,dd);dl.append(group);}return dl;}

 function avatar(u){let parsed;try{parsed=new URL(u.photoURL);}catch(_){}if(safeOrganizationImage(u.photoURL,u.uid)){const img=node('img','ad-avatar');img.src=parsed.href;img.alt=u.name+' profile photo';img.loading='lazy';img.referrerPolicy='no-referrer';img.addEventListener('error',()=>img.replaceWith(initials(u)),{once:true});return img;}return initials(u);}

 function initials(u){return node('span','ad-avatar',(u.name||u.organizationName||'MB').trim().split(/\s+/).slice(0,2).map(w=>w[0]).join('').toUpperCase());}

 function empty(region,title,copy){region.replaceChildren();const box=node('div','ad-section-empty');box.append(node('h2','',title),node('p','',copy));region.append(box);}

 function loading(region,name){if(state[name].ready&&!state[name].error)return false;if(state[name].error)empty(region,'Connection needs attention.','Use Retry above to reconnect to Firestore.');else{region.innerHTML='<div class="db-skeleton" aria-hidden="true"></div><div class="db-skeleton" aria-hidden="true"></div>';region.setAttribute('aria-busy','true');}return true;}

 function renderErrors(){const region=$('#admin-errors');region.replaceChildren();for(const name of names)if(state[name].error){const box=node('div','ad-alert',`${name}: ${adminError(state[name].error)}`),b=node('button','db-text-button','Retry');b.type='button';b.dataset.retry=name;box.append(b);region.append(box);}$('#admin-sync').textContent=names.some(n=>state[n].error)?'Connection needs attention':names.some(n=>!state[n].ready)?'Connecting Firestore':names.some(n=>state[n].cache)?'Cached data · reconnect to moderate':'Live · synced to Firestore';}

 function updateMetrics(){const loaded=['users','listings','claims'].every(name=>state[name].ready&&!state[name].error),values=adminMetrics(state.users.items,state.listings.items,state.claims.items);$$('[data-metric]').forEach(el=>el.textContent=loaded?values[el.dataset.metric].toLocaleString('en-US'):'—');$('#admin-meals').textContent=loaded?values.meals.toLocaleString('en-US'):'—';if(loaded&&!animated){animated=true;for(const el of $$('[data-metric]')){const value=values[el.dataset.metric],counter={value:value*.85};animate({targets:counter,value,duration:650,easing:'easeOutExpo',update:()=>el.textContent=Math.round(counter.value).toLocaleString('en-US'),complete:()=>{if(!dead)el.textContent=adminMetrics(state.users.items,state.listings.items,state.claims.items)[el.dataset.metric].toLocaleString('en-US');}});}animate({targets:$$('.ad-metrics .db-stat'),translateY:[8,0],delay:window.anime?anime.stagger(30):0,duration:450,easing:'easeOutExpo'});}}

 function queue(){const region=$('#admin-queue');if(loading(region,'users'))return;region.setAttribute('aria-busy','false');const users=organizationFilter(state.users.items,{state:verificationTab});$('#queue-count').textContent=`${users.length} ${users.length===1?'organization':'organizations'} in this review view`;region.replaceChildren();if(!users.length){empty(region,'Every review makes the bridge stronger.',verificationTab==='pending'?'No pending organizations need review.':'No organizations in this verification state.');return;}for(const u of users){const card=node('article','db-panel ad-organization'),identity=node('div','ad-identity');identity.append(avatar(u),node('h2','',u.organizationName));card.append(identity,badge(verificationState(u)),fields([['Contact name',u.name],['Email',u.email],['Phone',u.phone],['Agra locality',u.locality],['Role',role(u.role)],['Submitted',date(u.verificationRequestedAt||u.createdAt)]]));const actions=node('div','ad-actions');actions.append(button('Verify Organization','verify',u.uid,!fresh('users'),'button primary'),button(verificationState(u)==='rejected'?'Reopen / review':'Reject / review','review',u.uid,!fresh('users'),'button secondary'),button('View details','organization',u.uid));card.append(actions);region.append(card);}}

 function table(region,headers,rows,label){region.replaceChildren();if(!rows.length){empty(region,'More data will appear as MealBridge grows.','No records match this view. Try another filter.');return;}const wrap=node('div','ad-table-wrap'),table=node('table','ad-table');table.setAttribute('role','table');table.setAttribute('aria-label',label);const thead=node('thead'),head=node('tr');for(const text of headers){const th=node('th','',text);th.scope='col';head.append(th);}thead.append(head);const body=node('tbody');for(const cells of rows){const row=node('tr');row.setAttribute('role','row');cells.forEach((content,index)=>{const td=node('td');td.setAttribute('role','cell');td.dataset.label=headers[index];const holder=node('div');if(typeof content==='string')holder.textContent=content;else holder.append(content);td.append(holder);row.append(td);});body.append(row);}table.append(thead,body);wrap.append(table);region.append(wrap);}

 function paginated(items,name){const total=Math.ceil(items.length/25);pages[name]=Math.min(pages[name],Math.max(0,total-1));const region=$('#'+({directory:'directory-pages',listings:'listing-pages',claims:'claim-pages'}[name]));region.replaceChildren();if(total>1){const prev=button('Previous','page-'+name,'',pages[name]===0),next=button('Next','page-'+name,'',pages[name]>=total-1);prev.dataset.delta=-1;next.dataset.delta=1;region.append(prev,node('span','',`Page ${pages[name]+1} of ${total} · ${items.length} records`),next);}else region.append(node('span','',`${items.length} records`));return items.slice(pages[name]*25,(pages[name]+1)*25);}

 function identityCell(u){const cell=node('div');cell.append(avatar(u),node('strong','',u.organizationName),node('p','',u.name));return cell;}

 function directory(){const region=$('#admin-directory');if(loading(region,'users'))return;const items=organizationFilter(state.users.items,{search:$('#directory-search').value,role:$('#directory-role').value,state:$('#directory-state').value});const rows=paginated(items,'directory').map(u=>{const contact=node('div');contact.append(node('span','',u.email),node('p','',u.phone));const status=node('div');status.append(badge(verificationState(u)),node('p','',date(u.createdAt)));const actions=node('div','ad-actions');actions.append(button('Details','organization',u.uid),button('Review','review',u.uid,!fresh('users')));return[identityCell(u),contact,role(u.role)+' · '+u.city,status,actions];});table(region,['Organization','Contact','Role / City','Verification / Joined','Actions'],rows,'Organization directory');}

 function listings(){const region=$('#admin-listings');if(loading(region,'listings'))return;const search=$('#listing-search').value.trim().toLocaleLowerCase(),filter=$('#listing-state').value,items=state.listings.items.filter(l=>(filter==='all'||listingStatus(l)===filter)&&(!search||[l.foodName,l.hostelName,l.location?.city].some(v=>String(v||'').toLocaleLowerCase().includes(search)))).sort((a,b)=>timestampMillis(b.createdAt)-timestampMillis(a.createdAt));

 const rows=paginated(items,'listings').map(l=>{const identity=node('div'),img=node('img','ad-food-thumb');img.src=safeFoodImage(l.foodImage,l.foodImagePath,l.hostelId,l.id);img.alt=l.foodName;img.loading='lazy';img.addEventListener('error',()=>{img.src='assets/images/hero-meal.jpg';},{once:true});identity.append(img,node('strong','',l.foodName),node('p','',FOOD_LABELS[l.foodType]||l.foodType));const provider=node('div');provider.append(node('span','',l.hostelName),node('p','',l.location?.city||'Unknown city'),node('p','',`Owner: ${l.hostelId}`),badge(partner(l.hostelId)?.isVerified?'verified':'pending'));const timing=node('div');timing.append(node('span','',`Expires ${date(l.expiryTime)}`),node('p','',`Created ${date(l.createdAt)}`));const availability=node('div');availability.append(node('strong','',`${l.availableBoxes} / ${l.totalBoxes} boxes`),node('p','',listingStatus(l)));const actions=node('div','ad-actions'),canPause=fresh('listings')&&['available','partiallyClaimed'].includes(l.status)&&timestampMillis(l.expiryTime)>Date.now()&&l.availableBoxes>0;actions.append(button('Details','listing',l.id),button(l.isPaused?'Resume':'Pause',l.isPaused?'resume':'pause',l.id,!canPause),button('Cancel','cancel',l.id,!fresh('listings')||['collected','cancelled'].includes(l.status)));return[identity,provider,availability,timing,actions];});table(region,['Food','Provider / City','Boxes / Status','Timing','Actions'],rows,'Listings moderation');}

 function claims(){const region=$('#admin-claims');if(loading(region,'claims'))return;const filter=$('#claim-state').value,items=state.claims.items.filter(c=>filter==='all'||c.claimStatus===filter).sort((a,b)=>timestampMillis(b.createdAt)-timestampMillis(a.createdAt));const rows=paginated(items,'claims').map(c=>{const listing=food(c.listingId),identity=node('div');identity.append(node('strong','',listing?.foodName||'Listing '+c.listingId),node('p','',listing?.hostelName||partner(c.hostelId)?.organizationName||c.hostelId));const timing=node('div');timing.append(node('span','',`ETA ${date(c.pickupETA)}`),node('p','',`Created ${date(c.createdAt)}`));return[c.ngoName,identity,String(c.requestedBoxes),badge(({enRoute:'en route'}[c.claimStatus])||c.claimStatus),timing];});table(region,['NGO','Food / Hostel','Boxes','Status','Pickup / Created'],rows,'Claims monitoring, read only');}

 function distribution(title,values){const figure=node('figure','db-panel');figure.append(node('h2','',title));const total=values.reduce((sum,[,n])=>sum+n,0);figure.append(node('p','ad-chart-total',`${total} records`));if(!total){figure.append(node('p','ad-note','More data will appear as MealBridge grows.'));return figure;}for(const [label,value]of values){const row=node('div','ad-chart-row');row.append(node('span','',label),node('strong','',value.toLocaleString('en-US')));const track=node('div','ad-chart-track'),fill=node('div','ad-chart-fill');track.setAttribute('role','img');track.setAttribute('aria-label',`${label}: ${value} of ${total}`);fill.style.width=value/total*100+'%';track.append(fill);row.append(track);figure.append(row);}return figure;}

 function analytics(){const charts=$('#admin-charts');charts.replaceChildren();if(!['users','listings','claims'].every(n=>state[n].ready&&!state[n].error)){empty(charts,'Waiting for actual data.','Connect all three collections to calculate distributions.');return;}const users=state.users.items.filter(u=>['hostel','ngo'].includes(u.role)),foods=state.listings.items,values=adminMetrics(state.users.items,foods,state.claims.items);charts.append(distribution('Partner role distribution',[['Hostel',users.filter(u=>u.role==='hostel').length],['NGO',users.filter(u=>u.role==='ngo').length]]),distribution('Organization verification',['pending','verified','rejected'].map(s=>[s[0].toUpperCase()+s.slice(1),users.filter(u=>verificationState(u)===s).length])),distribution('Listing status',['Available','Partially Claimed','Paused','Claimed','Collected','Cancelled','Expired'].map(s=>[s,foods.filter(l=>listingStatus(l)===s).length])),distribution('Food type distribution',Object.entries(FOOD_LABELS).map(([key,label])=>[label,foods.filter(l=>l.foodType===key).length])));const summary=node('div','db-panel');summary.append(node('h2','','Claimed boxes & impact'),fields([['Claimed boxes',String(values.boxes)],['Collected boxes',String(foods.reduce((sum,l)=>sum+(l.collectedBoxes||0),0))],['Estimated meals collected',String(values.meals)],['Meaning','Collected boxes × approximate meals per box; not measured distribution']]));charts.append(summary);

 const events=[...state.users.items.map(u=>({time:timestampMillis(u.createdAt),text:`New ${role(u.role)} account · ${u.organizationName||u.name}`})),...foods.map(l=>({time:timestampMillis(l.createdAt),text:`New listing · ${l.foodName}`})),...state.claims.items.map(c=>({time:timestampMillis(c.createdAt),text:`New claim · ${c.ngoName} · ${c.requestedBoxes} boxes`})),...state.adminActivity.items.map(e=>({time:timestampMillis(e.createdAt),text:e.targetKind==='organization'?`Organization ${e.action} · ${partner(e.targetId)?.organizationName||e.targetId}`:`Listing ${e.action} · ${food(e.targetId)?.foodName||e.targetId}`}))].filter(e=>e.time>0).sort((a,b)=>b.time-a.time).slice(0,25);const region=$('#admin-activity');region.replaceChildren();if(!events.length)region.append(node('li','','More data will appear as MealBridge grows.'));for(const e of events){const li=node('li'),time=node('time','',date(e.time));time.dateTime=new Date(e.time).toISOString();li.append(node('span','',e.text),time);region.append(li);}}

 function renderPanel(){const focused=document.activeElement,action=focused?.dataset.action,id=focused?.dataset.id;({overview:()=>{},verification:queue,directory,listings,claims,analytics}[panel])();if(action&&id){const b=$(`[data-action="${CSS.escape(action)}"][data-id="${CSS.escape(id)}"]`);if(b&&!b.disabled)b.focus({preventScroll:true});}if($('#admin-detail').open)void refreshDetail(false);}

 function connect(name){const entry=state[name];entry.stop?.();entry.ready=false;entry.cache=true;entry.error=null;entry.items=[];const generation=++entry.generation;renderErrors();updateMetrics();renderPanel();try{entry.stop=repository.watch(name,(items,meta)=>{if(dead||generation!==entry.generation)return;entry.items=items;entry.ready=true;entry.cache=meta.fromCache;entry.error=null;renderErrors();updateMetrics();renderPanel();},error=>{if(dead||generation!==entry.generation)return;entry.error=error;entry.items=[];entry.ready=false;renderErrors();updateMetrics();renderPanel();});}catch(error){entry.error=error;renderErrors();renderPanel();}}

 const detail=$('#admin-detail'),confirm=$('#admin-confirm');let detailTarget;

 function open(dialog){opener=document.activeElement;dialog.showModal();document.body.classList.add('db-dialog-open');dialog.querySelector('[tabindex="-1"]').focus();animate({targets:dialog.querySelector('.db-wizard-shell'),translateY:[8,0],duration:250,easing:'easeOutExpo'});}

 for(const dialog of [detail,confirm])on(dialog,'close',()=>{document.body.classList.remove('db-dialog-open');if(dialog===detail)detailToken++;if(opener?.isConnected&&opener.getClientRects().length&&!opener.disabled)opener.focus();else $(`#${panel}-title`).focus({preventScroll:true});});on(confirm,'cancel',e=>{if(busy)e.preventDefault();});

 async function refreshDetail(readPrivate=true){if(!detailTarget)return;const {kind,id}=detailTarget,item=kind==='organization'?partner(id):food(id),region=$('#admin-detail-content');if(!item){region.replaceChildren(node('p','','This record is no longer in the loaded collection.'));$('#admin-detail-private').replaceChildren();return;}region.replaceChildren();$('#admin-detail-title').textContent=kind==='organization'?item.organizationName:item.foodName;if(kind==='organization'){region.append(badge(verificationState(item)),fields([['Contact name',item.name],['Email',item.email],['Phone',item.phone],['City',item.city],['Role',role(item.role)],['Joined',date(item.createdAt)],['Last reviewed',date(item.verificationReviewedAt)],['Verified by',item.verifiedBy||'Not verified']]));}else{const img=node('img','ad-food-photo');img.src=safeFoodImage(item.foodImage,item.foodImagePath,item.hostelId,id);img.alt=item.foodName;region.append(img,fields([['Provider',item.hostelName],['Owner',item.hostelId],['City',item.location?.city],['Available / total',`${item.availableBoxes} / ${item.totalBoxes} boxes`],['Claimed / collected',`${item.claimedBoxes} / ${item.collectedBoxes||0} boxes`],['Food type',FOOD_LABELS[item.foodType]],['State',listingStatus(item)],['Expiry',date(item.expiryTime)],['Packing',item.packingCondition],['Allergens',item.allergens]]));}if(!readPrivate)return;const token=++detailToken,privateRegion=$('#admin-detail-private');privateRegion.replaceChildren(node('p','ad-note','Loading restricted details…'));try{const data=await repository.details(kind==='organization'?'organizationModeration':'listingPrivate',id);if(dead||token!==detailToken||!detail.open)return;privateRegion.replaceChildren();if(kind==='organization')privateRegion.append(fields([['Internal review note',data?.internalNote||'No internal note recorded'],['Reviewed by',data?.reviewedBy||'No reviewer']]));else{const pickup=data||{exactAddress:item.location?.address,contactPerson:item.contactPerson,additionalPickupInstructions:item.notes};privateRegion.append(fields([['Exact pickup address',pickup.exactAddress],['Contact person',pickup.contactPerson],['Contact phone',pickup.contactPhone],['Pickup instructions',pickup.additionalPickupInstructions]]));}}catch(error){if(!dead&&token===detailToken){privateRegion.replaceChildren(node('p','ad-alert',adminError(error)));const b=button('Retry restricted details','retry-detail',id);privateRegion.append(b);}}}

 function requestAction(action,id){operation={action,id};$('#admin-action-error').hidden=true;$('#admin-inline-toast').replaceChildren();$('#admin-confirm-form').reset();const organization=['verify','review'].includes(action);$('#admin-review-fields').hidden=!organization;$('#admin-review-state').value=action==='verify'?'verified':'rejected';$('#admin-confirm-title').textContent=organization?'Review this organization.':action==='cancel'?'Cancel this food listing.':action==='pause'?'Pause this listing.':'Resume this listing.';$('#admin-confirm-copy').textContent=organization?`Confirm your decision for ${partner(id)?.organizationName||'this organization'}. Internal notes are private to the administrator.`:action==='cancel'?`Cancel ${food(id)?.foodName||'this listing'}? Discovery and pickup access will stop. Existing claim records and quantities remain unchanged; no claim cancellation or reallocation is performed.`:`Confirm ${action} for ${food(id)?.foodName||'this listing'}. Ownership and quantities will remain unchanged.`;open(confirm);}

 function setBusy(value){busy=value;$('#admin-confirm-form').setAttribute('aria-busy',value);$$('#admin-confirm button,#admin-confirm select,#admin-confirm textarea').forEach(el=>el.disabled=value);$('#admin-confirm-submit').textContent=value?'Saving decision…':'Confirm action';}

 on($('#admin-confirm-form'),'submit',async e=>{e.preventDefault();if(busy)return;setBusy(true);$('#admin-action-error').hidden=true;const {action,id}=operation;try{if(['verify','review'].includes(action))await repository.verify(id,$('#admin-review-state').value,$('#admin-review-note').value,$('#admin-public-note').value);else await repository.moderate(id,action);if(dead)return;setBusy(false);confirm.close();toast(['verify','review'].includes(action)?'Organization review saved. The directory is synced.':`Listing ${action==='cancel'?'cancelled':action==='pause'?'paused':'resumed'}. Its record is preserved.`);}catch(error){if(!dead){$('#admin-action-error').hidden=false;$('#admin-action-error').textContent=adminError(error);}}finally{if(!dead)setBusy(false);}});

 on(root,'click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.verificationTab){verificationTab=b.dataset.verificationTab;$$('[data-verification-tab]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));queue();}if(b.dataset.panel)showPanel(b.dataset.panel);if(b.dataset.retry)connect(b.dataset.retry);if(b.hasAttribute('data-close-detail'))detail.close();if(b.hasAttribute('data-close-confirm')&&!busy)confirm.close();if(b.dataset.directoryTab){const tab=b.dataset.directoryTab;$('#directory-role').value=['hostel','ngo'].includes(tab)?tab:'all';$('#directory-state').value=['pending','verified','rejected'].includes(tab)?tab:'all';$$('[data-directory-tab]').forEach(el=>el.setAttribute('aria-pressed',el===b));pages.directory=0;directory();}if(b.dataset.action){const action=b.dataset.action,id=b.dataset.id;if(['organization','listing'].includes(action)){detailTarget={kind:action,id};$('#admin-detail-title').textContent='Loading details.';open(detail);void refreshDetail();}else if(action==='retry-detail')void refreshDetail();else if(action.startsWith('page-')){const target=action.slice(5);pages[target]+=Number(b.dataset.delta);renderPanel();}else requestAction(action,id);}if(b.hasAttribute('data-signout')){b.disabled=true;closeMenu();logout().catch(error=>{if(!dead){b.disabled=false;toast(adminError(error));}});}});

 for(const id of ['directory-search','directory-role','directory-state','listing-search','listing-state','claim-state'])on($('#'+id),id.endsWith('search')?'input':'change',()=>{pages.directory=pages.listings=pages.claims=0;renderPanel();});

 const timer=setInterval(()=>{if(!document.hidden&&!dead){updateMetrics();if(['listings','analytics'].includes(panel))renderPanel();}},15000);on(document,'visibilitychange',()=>{if(!document.hidden){updateMetrics();renderPanel();}});on(motion,'change',()=>{if(motion.matches){for(const a of [...animations]){a.pause();a.seek(a.duration);}animations.clear();}});

 // Four shared listeners are reused across panels; no duplicate subscriptions.

 // Full collections make totals exact for this project; see PHASE7.md for scale limits.

 const engagement=mountEngagement(root,{sdk,user,profile,toast,onContext:n=>showPanel(n.relatedClaimId?'claims':n.relatedListingId?'listings':'directory')});

 for(const name of names)connect(name);

 return()=>{dead=true;engagement.destroy();detailToken++;for(const entry of Object.values(state)){entry.generation++;entry.stop?.();entry.items=[];}clearInterval(timer);clearTimeout(toastTimer);abort.abort();for(const a of animations)a.pause();animations.clear();for(const dialog of [detail,confirm])if(dialog.open)dialog.close();document.body.classList.remove('db-dialog-open');};

}

