import {getFirebase} from './firebase-config.js';
import {createProfileRepository,isAdminIdentity} from './profiles.js';
import {adminAccess,createAdminRepository} from './admin-data.js';
const root=document.getElementById('admin-root'),gate=document.getElementById('access-gate'),title=document.getElementById('access-title'),message=document.getElementById('access-message'),retry=document.getElementById('gate-retry');
let sdk,user,generation=0,cleanup,unsubscribe,redirect;
function conceal(){clearTimeout(redirect);cleanup?.();cleanup=undefined;root.hidden=true;root.replaceChildren();gate.hidden=false;document.querySelector('.skip-link').href='#access-gate';}
function restricted(){title.textContent='Access Restricted';message.textContent='This command center is reserved for the authorized MealBridge Google account. Returning to MealBridge in five seconds.';redirect=setTimeout(()=>location.replace('index.html#join'),5000);}
async function check(nextUser){const token=++generation;user=nextUser;conceal();retry.hidden=true;if(!isAdminIdentity(user)){restricted();return;}title.textContent='Verifying administrator access.';message.textContent='Checking your signed-in identity and saved profile…';try{const profile=await createProfileRepository(sdk).read(user);if(token!==generation)return;if(!adminAccess(user,profile)){restricted();return;}const {mountAdmin}=await import('./admin.js');if(token!==generation)return;cleanup=mountAdmin(root,{sdk,user,profile,repository:createAdminRepository(sdk,{user,profile}),logout:()=>sdk.signOut(sdk.auth)});root.hidden=false;gate.hidden=true;document.querySelector('.skip-link').href='#admin-main';}catch(error){if(token!==generation)return;title.textContent='Administrator connection unavailable.';message.textContent='We could not load your MealBridge profile. Check your connection and try again.';retry.textContent='Retry Profile Connection';retry.hidden=false;}}
async function initialize(){unsubscribe?.();unsubscribe=undefined;try{sdk=await getFirebase();unsubscribe=sdk.onAuthStateChanged(sdk.auth,u=>void check(u),()=>{++generation;conceal();restricted();});}catch(_){title.textContent='Connection unavailable.';message.textContent='Firebase could not be reached. Reconnect and retry.';retry.hidden=false;}}
retry.addEventListener('click',()=>{if(sdk)void check(user);else void initialize();});window.addEventListener('pagehide',()=>{++generation;unsubscribe?.();conceal();});window.addEventListener('pageshow',event=>{if(event.persisted)void initialize();});void initialize();
