import {validateAgraPlace,COVERAGE_ERROR} from './service-region.js';
import {mapServices} from './maps.js';
const cache=new Map(),pending=new Map();let tail=Promise.resolve(),last=0,cooldown=0;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
export function extractPlace(item){const a=item.address||{},city=a.city||a.town||a.village||a.municipality||a.county||a.state||'',locality=a.suburb||a.neighbourhood||a.quarter||a.city_district||a.village||a.town||city;return {state:String(a.state||''),country:a.country_code==='in'?'India':String(a.country||''),address:String(item.display_name||'').slice(0,240),city:String(city).slice(0,120),locality:String(locality).slice(0,120),latitude:Number(item.lat),longitude:Number(item.lon)};}
export function searchAddress(query){const q=String(query).trim().replace(/\s+/g,' '),key=q.toLocaleLowerCase();if(q.length<3||q.length>240)return Promise.reject(Error('Search a public address, city or locality using 3–240 characters.'));if(cache.has(key))return Promise.resolve(cache.get(key));if(pending.has(key))return pending.get(key);
 async function request(){if(Date.now()<cooldown)throw Error('Address search is busy. Wait at least a minute, then search again.');const c=await mapServices();await wait(Math.max(0,1100-(Date.now()-last)));try{const stored=Number(localStorage.getItem('mealbridge:geocoder-last')||0);await wait(Math.max(0,1100-(Date.now()-Math.min(Date.now(),stored))));}catch(_){}last=Date.now();try{localStorage.setItem('mealbridge:geocoder-last',String(last));}catch(_){}
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const url=new URL(c.geocoder);for(const [k,v]of Object.entries({q,format:'jsonv2','accept-language':'en',addressdetails:'1',limit:'5'}))url.searchParams.set(k,v);const response=await fetch(url,{signal:controller.signal,referrerPolicy:'strict-origin-when-cross-origin'});if(response.status===429){cooldown=Date.now()+60000;throw Error('Address search is busy. Wait at least a minute, then search again.');}if(!response.ok)throw Error('Address search is temporarily unavailable. Wait and retry, or adjust an existing pin.');const data=await response.json();if(!Array.isArray(data))throw Error('Address search returned an unexpected response.');const results=data.map(extractPlace).filter(p=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)&&Math.abs(p.latitude)<=90&&Math.abs(p.longitude)<=180);cache.set(key,results);if(cache.size>50)cache.delete(cache.keys().next().value);return results;}catch(e){if(e.name==='AbortError')throw Error('Address search timed out. Retry when connected.');if(e instanceof TypeError||e instanceof SyntaxError)throw Error('Address search could not connect. Check your connection and try again.');throw e;}finally{clearTimeout(timer);}}
 // Serial within this tab; Web Locks serialize cooperating same-origin tabs.
 const task=tail.then(()=>navigator.locks?.request?navigator.locks.request('mealbridge-geocoding',request):request());tail=task.catch(()=>{});pending.set(key,task);return task.finally(()=>pending.delete(key));
}
export function mountAddressSearch(region,{label='Search a public address or locality',agraOnly=false,onSelect,onInvalid=()=>{}}){region.innerHTML='<div class="mb-address-search"><label></label><div class="mb-search-row"><input type="search" maxlength="240" placeholder="City, locality or public business address"><button type="button" class="button secondary">Search Address</button></div><p class="mb-map-note">Search uses Nominatim / OpenStreetMap. Do not include private names or contact details.</p><p class="mb-search-status" role="status"></p><div class="mb-search-results"></div></div>';const input=region.querySelector('input'),button=region.querySelector('button'),status=region.querySelector('[role=status]'),results=region.querySelector('.mb-search-results'),id='mb-search-'+crypto.randomUUID();input.id=id;const text=region.querySelector('label');text.htmlFor=id;text.textContent=label;const abort=new AbortController();let dead=false,busy=false,revision=0,timer,choices=[];const on=(n,e,fn)=>n.addEventListener(e,fn,{signal:abort.signal});on(input,'input',()=>{revision++;if(agraOnly)onInvalid();results.replaceChildren();clearTimeout(timer);button.disabled=true;timer=setTimeout(()=>{if(!dead&&!busy)button.disabled=false;},1000);status.textContent='Press Search Address when you’re ready. No automatic search is sent.';});on(input,'keydown',e=>{if(e.key==='Enter'){e.preventDefault();if(!button.disabled)button.click();}});on(results,'click',e=>{const b=e.target.closest('[data-place-index]');if(!b)return;const item=choices[Number(b.dataset.placeIndex)];if(item){try{if(agraOnly)validateAgraPlace(item);onSelect(item);status.textContent='Agra location selected.';results.replaceChildren();choices=[];}catch(e){if(agraOnly)onInvalid();status.textContent=e.message;}}});on(button,'click',async()=>{if(busy)return;const token=revision;busy=true;button.disabled=true;status.textContent='Searching OpenStreetMap…';results.replaceChildren();try{const items=await searchAddress(input.value);if(dead||token!==revision)return;status.textContent=items.length?'Choose a result.':'No matching areas found. Try a city and locality.';choices=items;for(const [index,item]of items.entries()){const b=document.createElement('button');b.type='button';b.className='mb-place-result';b.textContent=item.address;b.dataset.placeIndex=index;results.append(b);}}catch(e){if(!dead&&token===revision)status.textContent=e.message;}finally{busy=false;if(!dead)button.disabled=false;}});return {setQuery(value){revision++;input.value=value;results.replaceChildren();choices=[];status.textContent='';},destroy(){dead=true;clearTimeout(timer);abort.abort();choices=[];results.replaceChildren();}};}

