let configuration,leafletPromise;
export function mapServices(){return configuration??=fetch('map-services.json',{cache:'default'}).then(r=>{if(!r.ok)throw Error('Map configuration could not be loaded. Retry when connected.');return r.json();}).then(c=>{for(const key of ['leafletCSS','leafletJS','tiles','geocoder','router'])if(typeof c[key]!=='string'||!c[key].startsWith('https://'))throw Error('Map services need a valid HTTPS configuration.');return c;}).catch(e=>{configuration=undefined;throw e;});}
export function loadLeaflet(){return leafletPromise??=mapServices().then(async c=>{
 const resource=(id,tag,url)=>new Promise((resolve,reject)=>{let n=document.getElementById(id);if(n?.dataset.ready==='true'){resolve();return;}if(n)n.remove();n=document.createElement(tag);n.id=id;const timer=setTimeout(()=>fail(),15000);function fail(){clearTimeout(timer);n.remove();reject(Error('The map library could not load. Reconnect and retry.'));}n.onload=()=>{clearTimeout(timer);n.dataset.ready='true';resolve();};n.onerror=fail;if(tag==='link'){n.rel='stylesheet';n.href=url;}else n.src=url;document.head.append(n);});
 await Promise.all([resource('mb-leaflet-css','link',c.leafletCSS),window.L?Promise.resolve():resource('mb-leaflet-js','script',c.leafletJS)]);if(!window.L)throw Error('The map library did not initialize.');return window.L;
}).catch(e=>{leafletPromise=undefined;throw e;});}
// One lazily initialized Leaflet map per workspace. Move this same viewport
// between public discovery and the protected route dialog; never duplicate it.
export function createMapViewport(){
 const element=document.createElement('div');element.className='mb-map';element.setAttribute('aria-label','Interactive OpenStreetMap');let map,L,tiles,layers,dead=false,host,currentError=()=>{},epoch=0;const abort=new AbortController();
 function theme(){element.dataset.theme=document.documentElement.dataset.theme;}
 document.addEventListener('mealbridge:theme',theme,{signal:abort.signal});theme();
 return {
  async attach(target,center={latitude:18.52,longitude:73.85},zoom=12,onError=()=>{}){const token=++epoch;host=target;currentError=onError;target.setAttribute('aria-busy','true');try{[L]=await Promise.all([loadLeaflet(),mapServices()]);if(dead||token!==epoch)return null;target.replaceChildren(element);if(!map){map=L.map(element,{scrollWheelZoom:false,zoomControl:true,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false}).setView([center.latitude,center.longitude],zoom);layers=L.layerGroup().addTo(map);}else map.setView([center.latitude,center.longitude],zoom,{animate:false});const c=await mapServices();if(dead||token!==epoch)return null;if(!tiles){tiles=L.tileLayer(c.tiles,{maxZoom:19,minZoom:2,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a> contributors',updateWhenIdle:true,keepBuffer:0});tiles.on('tileerror',()=>{if(!dead&&host)currentError('Map tiles are temporarily unavailable. Listings remain usable.');});}if(!map.hasLayer(tiles))tiles.addTo(map);theme();map.invalidateSize({animate:false});target.setAttribute('aria-busy','false');return this;}catch(e){if(!dead&&token===epoch){target.setAttribute('aria-busy','false');onError(e.message);}return null;}},
  clear(){layers?.clearLayers();map?.closePopup();},
  retryTiles(){tiles?.redraw();},
  center(point,zoom=13){if(map)map.setView([point.latitude,point.longitude],zoom,{animate:false});},
  marker(point,{type='veg',title='',popup,draggable=false,onDrag,origin=false,count=1}={}){if(!map)return;const shapes={veg:'<path d="M5 18C4 8 10 4 19 5c0 9-4 15-14 13Zm0 0 9-9"/>',nonVeg:'<path d="M4 12c6-7 12-7 15 0-3 7-9 7-15 0Zm0 0-3-4v8Zm11-2h.1"/>',mixed:'<path d="M5 5h6v6H5zm8 8h6v6h-6zM5 16h6m5-11v6"/>'};const icon=L.divIcon({className:'mb-pin'+(origin?' mb-pin-origin':''),html:count>1?`<span>${count}</span>`:`<svg viewBox="0 0 24 24" aria-hidden="true">${origin?'<circle cx="12" cy="12" r="5"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3"/>':shapes[type]||shapes.mixed}</svg>`,iconSize:[36,36],iconAnchor:[18,18]});const marker=L.marker([point.latitude,point.longitude],{icon,title,alt:title,keyboard:true,zIndexOffset:origin?-100:100,draggable}).addTo(layers);if(popup)marker.bindPopup(popup,{maxWidth:280,minWidth:210});marker.on('add',()=>marker.getElement()?.setAttribute('aria-label',title));marker.getElement()?.setAttribute('aria-label',title);if(onDrag)marker.on('dragend',()=>{const p=marker.getLatLng();onDrag({latitude:p.lat,longitude:p.lng});});return marker;},
  route(line){if(!map)return;const route=L.geoJSON(line,{style:{color:'#079b68',weight:5,opacity:.9}}).addTo(layers);map.fitBounds(route.getBounds(),{padding:[28,28],maxZoom:16,animate:false});},
  detach(){++epoch;layers?.clearLayers();map?.closePopup();if(map&&tiles)map.removeLayer(tiles);map?.setView([20,0],2,{animate:false});element.remove();if(host)host.setAttribute('aria-busy','false');host=null;},
  destroy(){dead=true;++epoch;abort.abort();map?.remove();element.remove();map=L=tiles=layers=host=null;}
 };
}
