import {AGRA_CENTER,serviceable} from './service-region.js';
import {createMapViewport} from './maps.js';
import {mountAddressSearch} from './location-search.js';
import {coordinates} from './location-model.js';
import {routeTo,navigationURL,clearRouteCache} from './routing.js';
import {safeFoodImage,FOOD_LABELS,timestampMillis} from './listing-model.js';
import {expiryState} from './dashboard-data.js';
export function mountNgoMaps(root,{sdk,user,onOrigin,onView,toast}){
 const $=s=>root.querySelector(s),map=createMapViewport(),abort=new AbortController(),on=(n,e,fn)=>n.addEventListener(e,fn,{signal:abort.signal});let origin=null,items=[],visible=false,attached=false,dead=false,generation=0,geoGeneration=0,valid=new Map(),routeClaim=null,exact=null,routeAbort,opener;
 const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 const routeDialog=document.createElement('dialog');routeDialog.id='mb-route';routeDialog.className='db-dialog mb-route-dialog';routeDialog.setAttribute('aria-labelledby','mb-route-title');routeDialog.innerHTML='<div class="db-wizard-shell"><button type="button" class="icon-button db-dialog-close" data-route-close aria-label="Close route">×</button><h2 id="mb-route-title" tabindex="-1">Your next handoff, within reach.</h2><p class="mb-map-note">Directions use your selected origin and the exact pickup pin. Clicking View Route shares those coordinates with public OSRM; navigation opens OpenStreetMap. Travel time is a driving estimate, without live traffic.</p><div id="mb-route-search"></div><p id="mb-route-status" role="status">Verifying your active collection…</p><div id="mb-route-map" class="mb-map-host"></div><p class="mb-map-attribution">© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a></p><div class="mb-map-actions"><button type="button" class="button secondary" id="mb-route-retry">Calculate / retry route</button><button type="button" class="button primary" id="mb-navigate" disabled>Navigate to Pickup</button></div></div>';root.append(routeDialog);
 const status=$('#mb-map-status'),routeStatus=$('#mb-route-status');on(root,'click',e=>{const b=e.target.closest('[data-map-listing]');if(b)onView(b.dataset.mapListing);});
 function setOrigin(point,label){if(dead)return;origin={latitude:point.latitude,longitude:point.longitude};status.textContent=`${label}. Distances use approximate public pins.`;$('#mb-clear-origin').hidden=false;onOrigin(origin);if(visible)map.center(origin,13);if(routeDialog.open){routeStatus.textContent='Starting area selected. Click Calculate route to request road directions.';$('#mb-navigate').disabled=!exact;}}
 const search=mountAddressSearch($('#mb-ngo-search'),{label:'Choose an Agra locality',agraOnly:true,onSelect:p=>setOrigin(p,p.locality||p.city||'Selected area')}),routeSearch=mountAddressSearch($('#mb-route-search'),{label:'Starting city or locality',onSelect:p=>setOrigin(p,p.locality||p.city||'Selected area')});
 on($('#mb-use-location'),'click',()=>{const token=++geoGeneration;$('#mb-use-location').disabled=true;status.textContent='Requesting your location…';if(!navigator.geolocation){status.textContent='Location is unavailable. Search a city or locality instead.';$('#mb-use-location').disabled=false;return;}navigator.geolocation.getCurrentPosition(p=>{if(dead||token!==geoGeneration)return;$('#mb-use-location').disabled=false;setOrigin({latitude:p.coords.latitude,longitude:p.coords.longitude},'Current location selected');},e=>{if(dead||token!==geoGeneration)return;$('#mb-use-location').disabled=false;status.textContent=e.code===1?'Location permission was denied. Search a city or locality instead.':'Your location could not be determined. Search an area or retry.';},{enableHighAccuracy:false,timeout:10000,maximumAge:60000});});
 on($('#mb-clear-origin'),'click',()=>{geoGeneration++;origin=null;$('#mb-clear-origin').hidden=true;status.textContent='Choose a starting area to calculate approximate distances.';onOrigin(null);if(visible){const p=items.find(i=>coordinates(i.publicLocation))?.publicLocation;map.center(p||AGRA_CENTER,p?12:2);draw();}});
 function draw(){if(!attached||!visible)return;map.clear();const groups=new Map();for(const item of items){const p=item.publicLocation;if(!coordinates(p))continue;const key=p.latitude+','+p.longitude;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(item);}for(const group of groups.values()){const first=group[0],popup=node('div','mb-food-popup');for(const item of group){const card=node('article'),img=node('img');img.src=safeFoodImage(item.foodImage,item.foodImagePath,item.hostelId,item.id);img.alt=item.foodName;img.loading='lazy';card.append(img,node('h3','',item.foodName),node('p','',`${item.hostelName} · ${item.hostelVerified?'Verified':'Verification pending'}`),node('p','',`${FOOD_LABELS[item.foodType]} · ${item.availableBoxes} boxes · ~${item.availableBoxes*item.mealsPerBox} meals`),node('p','',`Approximate pickup area · ${item.publicLocation.locality}, ${item.publicLocation.city}`),node('p','',`${expiryState(timestampMillis(item.expiryTime)).time} left`));const b=node('button','button secondary','View Listing');b.type='button';b.dataset.mapListing=item.id;card.append(b);popup.append(card);}map.marker(first.publicLocation,{type:first.foodType,count:group.length,title:`${group.length>1?group.length+' food listings':first.foodName} · Approximate pickup area`,popup});}if(origin)map.marker(origin,{origin:true,title:'Your selected starting location · not stored'});$('#mb-map-count').textContent=`${items.filter(i=>coordinates(i.publicLocation)).length} mapped listings · approximate areas`;
 }
 async function show(){if(dead||!visible)return;const token=++generation;$('#mb-map-retry').hidden=true;const center=origin||items.find(i=>coordinates(i.publicLocation))?.publicLocation||AGRA_CENTER;const result=await map.attach($('#mb-public-map'),center,coordinates(center)&&center.longitude!==0?12:2,message=>{if(!dead&&token===generation){status.textContent=message;$('#mb-map-retry').hidden=false;}});if(!dead&&visible&&token===generation&&result){attached=true;const current=origin||items.find(i=>coordinates(i.publicLocation))?.publicLocation;if(current)map.center(current,12);draw();}}
 on($('#mb-map-retry'),'click',()=>{map.retryTiles();status.textContent='Retrying map tiles…';void show();});
 function stopRoute(){routeAbort?.abort();routeAbort=null;routeClaim=exact=null;clearRouteCache();map.clear();map.detach();attached=false;$('#mb-route-map').replaceChildren();$('#mb-navigate').disabled=true;routeStatus.textContent='Route cleared.';}
 on(routeDialog,'close',()=>{stopRoute();document.body.classList.remove('db-dialog-open');if(opener?.isConnected&&opener.getClientRects().length)opener.focus();else $('#claims-title')?.focus();if(visible)void show();});on($('[data-route-close]'),'click',()=>routeDialog.close());
 async function verified(id){if(!valid.has(id))throw Error('This collection is no longer active. Private route details are unavailable.');const [claim,pickup]=await Promise.all([sdk.getDocFromServer(sdk.doc(sdk.db,'claims',id)),sdk.getDocFromServer(sdk.doc(sdk.db,'listingPrivate',valid.get(id).listingId))]);if(!claim.exists()||claim.data().ngoId!==user.uid||!['claimed','enRoute'].includes(claim.data().claimStatus)||!coordinates(pickup.data()?.exactLocation))throw Error('The provider has not added a valid pickup pin, or this claim is no longer active.');return pickup.data().exactLocation;}
 async function calculate(){if(!routeClaim||!routeDialog.open)return;routeAbort?.abort();routeAbort=new AbortController();const controller=routeAbort,id=routeClaim;$('#mb-route-retry').disabled=true;$('#mb-navigate').disabled=true;routeStatus.textContent='Verifying pickup access…';try{const target=await verified(id);if(dead||controller.signal.aborted||routeClaim!==id)return;exact=target;if(!origin){routeStatus.textContent='Search a starting area above, or use your location in food discovery.';return;}routeStatus.textContent='Calculating road route…';const result=await routeTo(origin,target,{signal:controller.signal});if(dead||controller.signal.aborted||routeClaim!==id||!valid.has(id))return;const view=await map.attach($('#mb-route-map'),origin,13,message=>{if(!dead&&routeClaim===id)routeStatus.textContent=message;});if(!view||dead||controller.signal.aborted)return;map.clear();map.marker(origin,{origin:true,title:'Your selected starting point'});map.marker(target,{title:'Exact pickup pin · active claim only'});map.route(result.geometry);routeStatus.textContent=`Route distance: ${result.distance.toFixed(1)} km · Estimated travel time: ${result.minutes} min`;$('#mb-navigate').disabled=false;}catch(e){if(!dead&&!controller.signal.aborted&&routeClaim===id){routeStatus.textContent=e.message;$('#mb-navigate').disabled=!origin||!exact;}}finally{if(!dead&&routeClaim===id)$('#mb-route-retry').disabled=false;}}
 on($('#mb-route-retry'),'click',()=>void calculate());on($('#mb-navigate'),'click',async()=>{if(!routeClaim||!origin)return;const id=routeClaim;const tab=window.open('about:blank','_blank');if(!tab){toast('Allow a new tab for OpenStreetMap directions, then retry.');return;}tab.opener=null;try{const target=await verified(id);if(dead||routeClaim!==id||!valid.has(id)){tab.close();return;}tab.location.replace(navigationURL(origin,target));}catch(e){tab.close();if(!dead)routeStatus.textContent=e.message;}});
 return {get origin(){return origin;},set(itemsNow){const wasMapped=items.some(i=>coordinates(i.publicLocation));items=itemsNow.filter(serviceable);if(visible){if(!attached)void show();else{const first=items.find(i=>coordinates(i.publicLocation))?.publicLocation;if(!wasMapped&&first)map.center(origin||first,12);draw();}}},setVisible(value){visible=value;generation++;if(!value){map.detach();attached=false;}else void show();},claims(rows){valid=new Map(rows.map(c=>[c.id,c]));if(routeClaim&&!valid.has(routeClaim)){if(routeDialog.open)routeDialog.close();else stopRoute();}},openRoute(claim){if(!valid.has(claim.id)){toast('Route access requires an active collection.');return;}opener=document.activeElement;routeClaim=claim.id;routeSearch.setQuery('');routeDialog.showModal();document.body.classList.add('db-dialog-open');$('#mb-route-title').focus();void calculate();},destroy(){dead=true;generation++;geoGeneration++;routeAbort?.abort();search.destroy();routeSearch.destroy();abort.abort();if(routeDialog.open)routeDialog.close();routeDialog.remove();valid.clear();items=[];origin=exact=null;clearRouteCache();map.destroy();}};
}
