import {collectionImpact,renderCollectionImpact} from './impact.js';
import {mountDirectory} from './directory.js';
import {serviceable,COVERAGE_ERROR} from './service-region.js';
import {coordinates,distanceLabel} from './location-model.js';
import {ngoTemplate} from './ngo-template.js';
import {icon} from './dashboard-template.js';
import {realFilters,filterRealListings,discoverable,claimMessage} from './claims.js';
import {FOOD_LABELS,safeFoodImage,DEFAULT_FOOD_IMAGE,timestampMillis} from './listing-model.js';
import {expiryState} from './dashboard-data.js';

import {mountEngagement} from './engagement.js';

export function mountNgo(root,{sdk,profile,user,repository,logout}){
 root.innerHTML=ngoTemplate();const directory=mountDirectory(root,{sdk,profile});const $=selector=>root.querySelector(selector),$$=selector=>[...root.querySelectorAll(selector)];
 const abort=new AbortController(),on=(target,event,fn)=>target.addEventListener(event,fn,{signal:abort.signal}),motion=matchMedia('(prefers-reduced-motion:reduce)'),mobile=matchMedia('(max-width:800px)'),animations=new Set();
 let listings=[],claims=[],filters=realFilters(),detailID,opener,ready=false,destroyed=false,toastTimer,panel='discover',cached=true,claimCached=true,busy=false,epoch=0;const stops=[],rows=new Map(),pending=new Set();
 function animate(options){if(motion.matches||!window.anime)return;let instance;const done=options.complete;instance=anime({...options,complete:()=>{animations.delete(instance);done?.();}});animations.add(instance);}
 const initials=name=>name.trim().split(/\s+/).slice(0,2).map(word=>word[0]).join('').toUpperCase();
 const time=value=>new Date(value).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});
 $('#ngo-account').textContent=profile.name;$('#ngo-avatar').textContent=initials(profile.name);$('#ngo-welcome').textContent=`Welcome, ${profile.organizationName}. A good meal can change someone’s day.`;
 $('#ngo-profile-org').textContent=profile.organizationName;$('#ngo-profile-email').textContent=user.email;$('#ngo-profile-avatar').textContent=initials(profile.organizationName);$('#ngo-verification').textContent=profile.isVerified?'Verified organization':'Awaiting organization verification';
 function descriptionList(target,pairs){target.replaceChildren();for(const [label,value]of pairs){const group=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;group.append(dt,dd);target.append(group);}}
 const locked=document.createElement('p');locked.className='role-lock';locked.textContent='Registered as NGO · Locked';$('#ngo-verification').after(locked);const note=document.createElement('p');note.className='db-settings-note';note.textContent='Your organization type is permanent after registration to protect platform trust and workflow integrity.';locked.after(note);if(!serviceable(profile))$('#ngo-welcome').textContent=COVERAGE_ERROR+' Your existing history remains available.';
 descriptionList($('#ngo-profile-data'),[['Organization',profile.organizationName],['Contact person',profile.name],['Phone',profile.phone],['City',profile.city]]);
 function toast(text){clearTimeout(toastTimer);const region=$('#ngo-detail').open?$('#detail-toast'):$('#ngo-toast');region.replaceChildren();const box=document.createElement('div');box.className='db-toast';const label=document.createElement('span');label.textContent=text;const close=document.createElement('button');close.type='button';close.textContent='×';close.setAttribute('aria-label','Dismiss notification');close.addEventListener('click',()=>box.remove(),{once:true});box.append(label,close);region.append(box);animate({targets:box,translateY:[8,0],duration:250,easing:'easeOutExpo'});toastTimer=setTimeout(()=>box.remove(),10000);}
 function syncTheme(){for(const select of [$('#ngo-theme'),$('#ngo-settings-theme')])select.value=MealBridgeTheme.preference;}
 on(document,'mealbridge:theme',syncTheme);syncTheme();for(const select of [$('#ngo-theme'),$('#ngo-settings-theme')])on(select,'change',()=>MealBridgeTheme.set(select.value));
 function closeMenu(restore=false){$('#ngo-sidebar').classList.remove('is-open');$('#ngo-sidebar').inert=mobile.matches;$('.db-body').inert=false;$('#ngo-menu').setAttribute('aria-expanded','false');$('#ngo-menu').setAttribute('aria-label','Open collector navigation');$('#ngo-scrim').hidden=true;document.body.classList.remove('db-dialog-open');if(restore)$('#ngo-menu').focus();}
 function showPanel(name){if(!['discover','claims','impact','settings','partners'].includes(name))return;$$('[data-section]').forEach(section=>section.hidden=section.dataset.section!==name);$$('.db-nav [data-panel]').forEach(button=>{if(button.dataset.panel===name)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});closeMenu();panel=name;directory.setVisible(name==='partners');connectPanel();window.scrollTo({top:0,behavior:'instant'});$(`[data-section="${name}"] h1`).focus({preventScroll:true});}
 on($('#ngo-menu'),'click',()=>{if($('#ngo-sidebar').classList.contains('is-open')){closeMenu(true);return;}$('#ngo-sidebar').inert=false;$('#ngo-sidebar').classList.add('is-open');$('.db-body').inert=true;$('#ngo-menu').setAttribute('aria-expanded','true');$('#ngo-menu').setAttribute('aria-label','Close collector navigation');$('#ngo-scrim').hidden=false;document.body.classList.add('db-dialog-open');$('.db-nav button').focus();animate({targets:$('.db-nav'),translateX:[-8,0],duration:250,easing:'easeOutExpo'});});
 on($('#ngo-scrim'),'click',()=>closeMenu(true));on(mobile,'change',()=>closeMenu());closeMenu();
 on(document,'keydown',event=>{if(!$('#ngo-sidebar').classList.contains('is-open'))return;if(event.key==='Escape'){event.preventDefault();closeMenu(true);}if(event.key==='Tab'){const controls=[...$('#ngo-sidebar').querySelectorAll('a,button')],first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
 const filterForm=$('#ngo-filter-form'),filterDialog=$('#ngo-filters'),detailDialog=$('#ngo-detail');
 const claimForm=$('#ngo-claim-form'),quantity=$('#claim-boxes');
 const localDate=value=>{const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,19);};
 const date=value=>new Date(timestampMillis(value)).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
 const activeClaim=claim=>['claimed','enRoute'].includes(claim.claimStatus);
 const normalize=item=>({...item,name:item.foodName,type:FOOD_LABELS[item.foodType],provider:item.hostelName,verified:item.hostelVerified===true,boxes:item.availableBoxes,meals:item.mealsPerBox,city:item.location.city,ready:timestampMillis(item.readyTime),expiry:timestampMillis(item.expiryTime),packing:item.packingCondition,image:safeFoodImage(item.foodImage,item.foodImagePath,item.hostelId,item.id)});
 function photo(item,className){const img=document.createElement('img');img.className=className;img.src=item.image;img.alt=item.image===DEFAULT_FOOD_IMAGE?'Default food photograph':item.name;img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>{img.src=DEFAULT_FOOD_IMAGE;},{once:true});return img;}
 function focusAfter(fn){const focused=document.activeElement,view=focused?.dataset.view,claim=focused?.dataset.claim,progress=focused?.dataset.progress,route=focused?.dataset.route;fn();const selector=view?`[data-view="${CSS.escape(view)}"]`:claim?`[data-claim="${CSS.escape(claim)}"]`:route?`[data-route="${CSS.escape(route)}"]`:progress?`[data-progress="${CSS.escape(progress)}"]`:null;if(selector){const target=$(selector);if(target&&!target.disabled)target.focus({preventScroll:true});else if(progress)$(`[data-claim-id="${CSS.escape(progress)}"] h2`)?.focus({preventScroll:true});}}
 function syncFilters(){for(const [key,value]of Object.entries(filters)){const control=filterForm.elements[key];if(!control)continue;if(control.type==='checkbox')control.checked=value;else control.value=value;}}
 function render(){
  if(!ready)return;const items=filterRealListings(listings,filters,user.uid,Date.now(),maps.origin),region=$('#ngo-listings');region.setAttribute('aria-busy','false');maps.set(items);
  focusAfter(()=>{region.replaceChildren();for(const raw of items){const item=normalize(raw),card=document.createElement('article');card.className='ng-card';card.dataset.listingId=item.id;const content=document.createElement('div');content.className='ng-card-content';
   const tag=document.createElement('span');tag.className='db-pill';tag.textContent=item.type+' · '+(item.status==='partiallyClaimed'?'Partially claimed':'Available');const title=document.createElement('h3');title.textContent=item.name;const provider=document.createElement('p');provider.className='ng-provider';provider.textContent=item.provider+' · '+(item.verified?'Verified organization':'Verification pending');
   const meta=document.createElement('dl');meta.className='ng-card-meta';descriptionList(meta,[['Available / total',`${item.boxes} / ${item.totalBoxes} boxes · ~${item.boxes*item.meals} meals`],['Approximate pickup area',raw.publicLocation?`${raw.publicLocation.locality}, ${raw.publicLocation.city}`:item.city],['Pickup ready',time(item.ready)],['Provider rating',engagement.summary(item.hostelId)]]);meta.querySelector('div:last-child dd').dataset.providerScore=item.hostelId;
   const urgency=document.createElement('p');urgency.className='db-urgency ng-card-expiry';const expiry=expiryState(item.expiry);urgency.dataset.tone=expiry.tone;urgency.textContent=`${expiry.time} left · ${expiry.label}`;
   const notes=document.createElement('p');notes.className='ng-provider';notes.textContent=`${item.packing} · Allergens: ${item.allergens}`;
   const actions=document.createElement('div');actions.className='ng-card-actions';for(const [action,label,style]of [['view','View Listing','secondary'],['claim','Claim Food','primary']]){const button=document.createElement('button');button.className='button '+style;button.dataset[action]=item.id;button.textContent=label;button.setAttribute('aria-label',label+': '+item.name);if(action==='claim')button.disabled=cached||claimCached||claims.some(c=>c.listingId===item.id);actions.append(button);}content.append(tag,title,provider,meta,urgency,notes,actions);card.append(photo(item,'ng-card-photo'),content);region.append(card);
  }});
  $('#ngo-result-count').textContent=cached?'Cached listings · reconnect to claim':`${items.length} ${filters.radius!=='any'&&maps.origin?'listings within '+filters.radius+' km':'active '+(items.length===1?'listing':'listings')} · Live`;$('#ngo-empty').hidden=items.length>0;$('#ngo-empty p').textContent=listings.length?'No verified surplus matches these filters.':'No verified surplus listings are available in Agra yet.';
  const defaults=realFilters(),count=Object.entries(filters).filter(([key,value])=>value!==defaults[key]).length;$('#filter-count').textContent=count;$('#filter-count').hidden=!count;
  if(detailDialog.open)updateDetail();
 }
 function openDialog(dialog){opener=document.activeElement;dialog.showModal();document.body.classList.add('db-dialog-open');dialog.querySelector('[tabindex="-1"]').focus();animate({targets:dialog.querySelector('.db-wizard-shell'),translateY:[8,0],duration:300,easing:'easeOutExpo'});}
 for(const dialog of [filterDialog,detailDialog])on(dialog,'close',()=>{document.body.classList.remove('db-dialog-open');if(opener?.isConnected&&opener.getClientRects().length)opener.focus();else $('[data-filters]').focus();});
 on(detailDialog,'cancel',event=>{if(busy)event.preventDefault();});
 function updateDetail(){const raw=listings.find(value=>value.id===detailID),valid=raw&&discoverable(raw,user.uid),existing=claims.some(c=>c.listingId===detailID);if(raw){const item=normalize(raw);descriptionList($('#detail-fields'),[['Food type',item.type],['Available / total',`${item.boxes} / ${item.totalBoxes} boxes · ~${item.boxes*item.meals} meals`],['Approximate pickup area',raw.publicLocation?`${raw.publicLocation.locality}, ${raw.publicLocation.city}`:item.city],['Pickup window',`${date(item.readyTime)} – ${date(item.expiryTime)}`],['Expiry countdown',`${expiryState(item.expiry).time} · ${expiryState(item.expiry).label}`],['Allergen notes',item.allergens],['Packing condition',item.packing],['Provider rating',engagement.summary(raw.hostelId)]]);quantity.max=item.boxes;$('#claim-eta').min=localDate(Math.max(Date.now(),item.ready));$('#claim-eta').max=localDate(item.expiry-1000);$('#claim-availability').textContent=`${item.boxes} boxes available · expires ${date(item.expiryTime)}`;}
  const blocked=!valid||cached||claimCached||existing;$('#detail-claim').disabled=blocked||busy;$('#detail-claim').textContent=existing?'Already claimed':blocked?'Unavailable':'Claim Food';$('#claim-confirm').disabled=blocked||busy;quantity.disabled=blocked||busy;$('#claim-eta').disabled=blocked||busy;$('#claim-note').disabled=blocked||busy;$$('[data-quantity]').forEach(button=>button.disabled=blocked||busy);$('[data-close-detail]').disabled=busy;if(!valid)$('#claim-availability').textContent='This listing is no longer available. Close this modal and review discovery.';
 }
 function showClaimForm(){claimForm.hidden=false;$('#detail-claim').hidden=true;quantity.focus();quantity.scrollIntoView({block:'center',behavior:motion.matches?'instant':'smooth'});}
 function openDetail(id,claim=false){const raw=listings.find(value=>value.id===id);if(!raw)return;const item=normalize(raw);detailID=id;$('#detail-title').textContent=item.name;$('#detail-image').src=item.image;$('#detail-provider').textContent=item.provider+' · '+(item.verified?'Verified organization':'Verification pending');$('#detail-notes').textContent='Hygienic handling confirmed by the provider.';$('#detail-toast').replaceChildren();claimForm.reset();$('#claim-error').hidden=true;claimForm.hidden=!claim;$('#detail-claim').hidden=claim;$('#claim-eta').value=localDate(Math.max(Date.now()+5000,item.ready+1000,Math.min(Date.now()+30*60000,(Math.max(Date.now(),item.ready)+item.expiry)/2)));updateDetail();openDialog(detailDialog);if(claim)showClaimForm();}
 on(claimForm,'submit',async event=>{event.preventDefault();if(busy||!claimForm.reportValidity())return;busy=true;$('#claim-error').hidden=true;$('#claim-confirm').textContent='Confirming claim…';updateDetail();try{await repository.claim(detailID,{requestedBoxes:quantity.value,pickupETA:Date.parse($('#claim-eta').value),ngoNote:$('#claim-note').value});if(destroyed)return;busy=false;detailDialog.close();showPanel('claims');toast('Claim confirmed. Your boxes are reserved — pickup details are in Active claims.');}catch(error){if(!destroyed){$('#claim-error').hidden=false;$('#claim-error').textContent=claimMessage(error);}}finally{if(!destroyed){busy=false;$('#claim-confirm').textContent='Confirm Claim';if(detailDialog.open)updateDetail();}}});
 on(filterForm,'submit',event=>{event.preventDefault();if(!filterForm.reportValidity())return;const data=new FormData(filterForm);filters={location:String(data.get('location')).trim(),type:data.get('type'),boxes:Number(data.get('boxes')),pickup:data.get('pickup'),urgent:filterForm.elements.urgent.checked,verified:true,sort:data.get('sort'),radius:'any'};render();filterDialog.close();toast('Discovery filters updated.');});
 on($('#filter-reset'),'click',()=>{filters=realFilters();syncFilters();render();});
 const engagement=mountEngagement(root,{sdk,user,profile,toast,onCollections:(items,meta)=>{renderCollectionImpact($('#ngo-chart'),items,meta);$('#ngo-boxes-collected').textContent=meta.fromCache?'—':collectionImpact(items).boxesThisMonth.toLocaleString();},onContext:n=>{showPanel(n.relatedClaimId?'claims':n.relatedListingId?'discover':'settings');if(n.relatedListingId&&!n.relatedClaimId)openDetail(n.relatedListingId);},onScore:()=>{if(detailDialog.open)updateDetail();}});
 // No map module is imported or initialized while location discovery is suspended.
 const maps={origin:null,set(){},claims(){},setVisible(){},destroy(){}};
 function stopPanel(){maps.claims([]);maps.set([]);maps.setVisible(false);epoch++;for(const stop of stops.splice(0))stop();for(const row of rows.values())row.stop?.();rows.clear();$('#ngo-active-claims').replaceChildren();}
 function claimError(error){$('#ngo-claims-error').hidden=false;$('#ngo-claims-error').textContent=claimMessage(error);$('[data-retry-claims]').hidden=false;$('#ngo-active-claims').setAttribute('aria-busy','false');}
 function renderClaims(){if(panel!=='claims')return;maps.claims(claimCached?[]:claims.filter(c=>{const row=rows.get(c.id);return activeClaim(c)&&row?.food&&row.food.status!=='cancelled'&&timestampMillis(row.food.expiryTime)>Date.now()&&!row.cached&&coordinates(row.privatePickup?.exactLocation);}));focusAfter(()=>{const region=$('#ngo-active-claims');region.replaceChildren();const active=claims.filter(activeClaim),recent=claims.filter(c=>c.claimStatus==='collected');if([...rows.values()].some(row=>row.error))$('[data-retry-claims]').hidden=false;$('#ngo-claims-empty').hidden=active.length+recent.length>0;region.setAttribute('aria-busy','false');
  for(const c of [...active,...recent]){const row=rows.get(c.id),raw=row?.food,item=raw?normalize(raw):null,allowed=activeClaim(c)&&raw&&raw.status!=='cancelled'&&timestampMillis(raw.expiryTime)>Date.now()&&!row.cached;const card=document.createElement('article');card.className='db-panel ng-live-claim';card.dataset.claimId=c.id;
   const heading=document.createElement('h2');heading.tabIndex=-1;heading.textContent=item?.name||'Loading food details…';if(item)card.append(photo(item,'ng-claim-photo'));const provider=document.createElement('p');provider.textContent=item?.provider||'Confirmed provider';const badge=document.createElement('span');badge.className='db-pill';badge.textContent={claimed:'Claimed',enRoute:'NGO en route',collected:'Collected'}[c.claimStatus]||c.claimStatus;card.append(heading,provider,badge);
   const journey=document.createElement('ol');journey.className='ng-journey';journey.setAttribute('aria-label','Pickup journey');for(const [index,label]of ['Claimed','NGO En Route','Collected','Impact Recorded · future'].entries()){const step=document.createElement('li');step.textContent=label;if(index===({claimed:0,enRoute:1,collected:2}[c.claimStatus])){step.className='is-current';step.setAttribute('aria-current','step');}journey.append(step);}card.append(journey);
   const dl=document.createElement('dl');dl.className='ng-detail-fields';descriptionList(dl,[['Reserved boxes',String(c.requestedBoxes)],['Pickup ETA',date(c.pickupETA)],['Your note',c.ngoNote||'No note']]);card.append(dl);
   const privateBlock=document.createElement('div');privateBlock.className='ng-private';const pickup=row?.privatePickup;if(allowed&&pickup){const detail=document.createElement('dl');detail.className='ng-detail-fields';descriptionList(detail,[['Exact pickup address',pickup.exactLocation?.address||pickup.exactAddress],['Contact person',pickup.contactPerson],['Contact phone',pickup.contactPhone||'Not provided'],['Pickup instructions',pickup.additionalPickupInstructions||'No additional instructions']]);privateBlock.append(detail);}else{const notice=document.createElement('p');notice.textContent=!activeClaim(c)?'Collection complete. Private pickup details are no longer available.':raw&&(raw.status==='cancelled'||timestampMillis(raw.expiryTime)<=Date.now())?'Pickup closed: this food is cancelled or expired. Do not collect it.':row?.error?'Pickup details could not be loaded. Retry claims.':'Verifying your active claim and pickup details…';privateBlock.append(notice);}card.append(privateBlock);
   const target=c.claimStatus==='claimed'?'enRoute':c.claimStatus==='enRoute'?'collected':null;if(target){const button=document.createElement('button');button.className='button '+(target==='collected'?'primary':'secondary');button.dataset.progress=c.id;button.dataset.target=target;button.textContent=pending.has(c.id)?'Updating…':target==='enRoute'?"I'm On The Way":'Food Collected';button.disabled=!allowed||claimCached||pending.has(c.id);card.append(button);}if(c.claimStatus==='collected')card.append(engagement.rateButton(c));region.append(card);
  }
 });}
 function attachRows(token){const ids=new Set(claims.map(c=>c.id));for(const [id,row]of rows)if(!ids.has(id)){row.stop();rows.delete(id);}
  for(const c of claims){if(rows.has(c.id)){const row=rows.get(c.id);if(!activeClaim(c))row.privatePickup=null;continue;}const row={food:null,privatePickup:null,request:0,cached:true};rows.set(c.id,row);row.stop=repository.watchListing(c.listingId,async(raw,meta)=>{if(token!==epoch||destroyed)return;const request=++row.request;row.food=raw;row.cached=meta.fromCache;row.privatePickup=null;row.error=false;renderClaims();const current=claims.find(value=>value.id===c.id);if(!raw||meta.fromCache||!current||!activeClaim(current)||raw.status==='cancelled'||timestampMillis(raw.expiryTime)<=Date.now())return;try{const pickup=await repository.readPrivate(c.listingId);if(token!==epoch||request!==row.request||destroyed||!activeClaim(claims.find(value=>value.id===c.id)||{}))return;row.privatePickup=pickup;renderClaims();}catch(error){if(token===epoch&&request===row.request&&!destroyed){row.privatePickup=null;row.error=true;renderClaims();}}},()=>{if(token===epoch&&!destroyed){row.food=null;row.privatePickup=null;row.error=true;renderClaims();}});}
 }
 function connectPanel(){stopPanel();const token=epoch;if(panel==='discover'&&!serviceable(profile)){$('#ngo-result-count').textContent=COVERAGE_ERROR;$('#ngo-listings').replaceChildren();return;}if(panel==='discover'){maps.setVisible(true);ready=false;cached=true;$('#ngo-empty').hidden=true;$('#ngo-list-error').hidden=true;$('[data-retry-listings]').hidden=true;$('#ngo-listings').innerHTML='<div class="db-skeleton" aria-hidden="true"></div><div class="db-skeleton" aria-hidden="true"></div>';$('#ngo-listings').setAttribute('aria-busy','true');stops.push(repository.watchListings((items,meta)=>{if(token!==epoch||destroyed)return;listings=items;cached=meta.fromCache;ready=true;engagement.setProviders(items.map(i=>i.hostelId));render();},error=>{if(token!==epoch||destroyed)return;listings=[];maps.set([]);ready=false;$('#ngo-listings').replaceChildren();$('#ngo-listings').setAttribute('aria-busy','false');$('#ngo-result-count').textContent='Discovery needs attention.';$('#ngo-list-error').hidden=false;$('#ngo-list-error').textContent=claimMessage(error);$('[data-retry-listings]').hidden=false;if(detailDialog.open)updateDetail();}));}
  if(['discover','claims'].includes(panel)){claimCached=true;$('#ngo-claims-error').hidden=true;$('[data-retry-claims]').hidden=true;if(panel==='claims'){$('#ngo-active-claims').innerHTML='<div class="db-skeleton" aria-hidden="true"></div>';$('#ngo-active-claims').setAttribute('aria-busy','true');$('#ngo-claims-empty').hidden=true;}stops.push(repository.watchClaims((items,meta)=>{if(token!==epoch||destroyed)return;claims=items;claimCached=meta.fromCache;$('#ngo-active-count').textContent=claims.filter(activeClaim).length;if(panel==='claims'){attachRows(token);renderClaims();}else if(ready)render();},error=>{if(token!==epoch||destroyed)return;claims=[];claimCached=true;$('#ngo-active-count').textContent='—';if(panel==='discover'){render();$('#ngo-list-error').hidden=false;$('#ngo-list-error').textContent='Your claims could not be checked. Reconnect and retry discovery before claiming.';$('[data-retry-listings]').hidden=false;}if(panel==='claims'){for(const row of rows.values())row.stop();rows.clear();$('#ngo-active-claims').replaceChildren();claimError(error);}}));}
 }
 on(root,'click',async event=>{const button=event.target.closest('button');if(!button||button.disabled)return;
  if(button.dataset.panel)showPanel(button.dataset.panel);
  if(button.hasAttribute('data-filters')){syncFilters();openDialog(filterDialog);}
  if(button.hasAttribute('data-close-filter'))filterDialog.close();if(button.hasAttribute('data-close-detail')&&!busy)detailDialog.close();
  if(button.hasAttribute('data-map-preview'))toast('Live maps and distance filters are coming soon.');
  if(button.hasAttribute('data-reset')){filters=realFilters();render();}
  
  if(button.dataset.view)openDetail(button.dataset.view);
  if(button.hasAttribute('data-claim')){if(button.id==='detail-claim')showClaimForm();else openDetail(button.dataset.claim,true);}
  if(button.dataset.quantity){quantity.value=Math.max(1,Math.min(Number(quantity.max),Number(quantity.value)+Number(button.dataset.quantity)));}
  if(button.hasAttribute('data-retry-listings')||button.hasAttribute('data-retry-claims'))connectPanel();
  if(button.dataset.progress){const id=button.dataset.progress;pending.add(id);renderClaims();try{await repository.progress(id,button.dataset.target);if(!destroyed){toast(button.dataset.target==='collected'?'Collection confirmed. Thank you for rescuing these meals.':'Your pickup is now marked en route.');if(button.dataset.target==='collected')engagement.openRating({...claims.find(c=>c.id===id),id,partnerName:rows.get(id)?.food?.hostelName,claimStatus:'collected'});}}catch(error){if(!destroyed)toast(claimMessage(error));}finally{if(!destroyed){pending.delete(id);renderClaims();}}}
  if(button.hasAttribute('data-signout')){button.disabled=true;closeMenu();logout().catch(()=>{if(destroyed)return;button.disabled=false;toast('Sign-out could not be completed. Check your connection and retry.');});}
 });
 $('#ngo-chart').textContent='Connecting your actual collection records…';
 connectPanel();if(location.hash==='#partners')showPanel('partners');
 const interval=setInterval(()=>{if(document.hidden||destroyed)return;if(panel==='discover'&&ready){const expired=$$('.ng-card').some(card=>timestampMillis(listings.find(item=>item.id===card.dataset.listingId)?.expiryTime)<=Date.now());if(expired)render();else $$('.ng-card').forEach(card=>{const item=listings.find(value=>value.id===card.dataset.listingId),state=expiryState(timestampMillis(item.expiryTime)),label=card.querySelector('.ng-card-expiry');label.textContent=`${state.time} left · ${state.label}`;label.dataset.tone=state.tone;});if(detailDialog.open)updateDetail();}if(panel==='claims')renderClaims();},15000);
 on(document,'visibilitychange',()=>{if(!document.hidden){if(panel==='discover'&&ready)render();if(panel==='claims')renderClaims();}});
 on(motion,'change',()=>{if(motion.matches){for(const instance of [...animations]){instance.pause();instance.seek(instance.duration);}animations.clear();}});
 return ()=>{destroyed=true;directory.destroy();stopPanel();maps.destroy();engagement.destroy();clearTimeout(toastTimer);clearInterval(interval);abort.abort();for(const instance of animations)instance.pause();animations.clear();for(const dialog of [filterDialog,detailDialog])if(dialog.open)dialog.close();document.body.classList.remove('db-dialog-open');};
}
