import {mapServices} from './maps.js';
import {coordinates} from './location-model.js';
const cache=new Map();let last=0,tail=Promise.resolve();
export function navigationURL(origin,destination){if(!coordinates(origin)||!coordinates(destination))throw Error('Choose your starting location and a valid pickup pin.');const url=new URL('https://www.openstreetmap.org/directions');url.searchParams.set('engine','fossgis_osrm_car');url.searchParams.set('route',`${origin.latitude},${origin.longitude};${destination.latitude},${destination.longitude}`);return url.href;}
export function routeTo(origin,destination,{signal}={}){if(!coordinates(origin)||!coordinates(destination))return Promise.reject(Error('Choose a starting location and valid exact pickup pin.'));const key=[origin.latitude,origin.longitude,destination.latitude,destination.longitude].join(',');if(cache.has(key))return Promise.resolve(cache.get(key));
 async function request(){if(cache.has(key))return cache.get(key);if(signal?.aborted)throw Error('Route request cancelled.');await new Promise(r=>setTimeout(r,Math.max(0,1100-(Date.now()-last))));if(signal?.aborted)throw Error('Route request cancelled.');last=Date.now();const config=await mapServices(),controller=new AbortController(),stop=()=>controller.abort(),timer=setTimeout(stop,15000);signal?.addEventListener('abort',stop,{once:true});try{const response=await fetch(`${config.router}/${origin.longitude},${origin.latitude};${destination.longitude},${destination.latitude}?overview=full&geometries=geojson&steps=false`,{signal:controller.signal,referrerPolicy:'strict-origin-when-cross-origin'});if(!response.ok)throw Error('Road routing is temporarily unavailable. Retry or open OpenStreetMap directions.');const data=await response.json(),route=data.routes?.[0];if(data.code!=='Ok'||!route||!Number.isFinite(route.distance)||!Number.isFinite(route.duration)||route.distance<0||route.duration<0||route.geometry?.type!=='LineString'||!Array.isArray(route.geometry.coordinates)||route.geometry.coordinates.length<2||route.geometry.coordinates.length>20000||!route.geometry.coordinates.every(p=>Array.isArray(p)&&coordinates({latitude:p[1],longitude:p[0]})))throw Error('No road route was found. Check the pickup pin or open OpenStreetMap directions.');const result={distance:route.distance/1000,minutes:Math.max(1,Math.ceil(route.duration/60)),geometry:route.geometry};if(signal?.aborted)throw Error('Route request cancelled.');cache.set(key,result);if(cache.size>20)cache.delete(cache.keys().next().value);return result;}catch(e){if(e.name==='AbortError')throw Error('The route could not be completed. Retry when connected.');if(e instanceof TypeError||e instanceof SyntaxError)throw Error('Road routing could not connect. Check your connection or use OpenStreetMap directions.');throw e;}finally{clearTimeout(timer);signal?.removeEventListener('abort',stop);}}
 const job=tail.then(request);tail=job.catch(()=>{});return job;
}
export function clearRouteCache(){cache.clear();}
